# Generated by Django 6.0.2 on 2026-02-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_blog_content_alter_blog_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_content', models.TextField(max_length=200)),
            ],
        ),
    ]
