# Generated by Django 6.0.2 on 2026-02-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='about us', max_length=50),
            preserve_default=False,
        ),
    ]
